#!/usr/bin/env bash
# mo purge — delete build artifacts (node_modules, target, __pycache__, ...)

run_purge() {
  local root="$HOME" arg
  for arg in "$@"; do
    [[ $arg == -* ]] && continue
    root="$arg"
  done
  root=$(realpath -m -- "$root" 2>/dev/null || echo "$root")
  [[ -d $root ]] || { err "not a directory: $root"; return 1; }
  SAFE_RM_ROOT="$root"   # user explicitly chose this tree; allow deletion inside it

  printf '%s\n' "${C_BOLD}mo purge${C_RESET} — build artifacts under ${C_CYAN}${root/#$HOME/\~}${C_RESET}$( (( DRY_RUN )) && printf ' %s' "${C_YELLOW}(dry run)${C_RESET}")"
  info "${C_DIM}scanning (this can take a moment)...${C_RESET}"

  local hits=() hit parent
  while IFS= read -r hit; do
    parent=$(dirname "$hit")
    case "$(basename "$hit")" in
      node_modules) [[ -f $parent/package.json ]] || continue ;;
      target)       [[ -f $parent/Cargo.toml   ]] || continue ;;
      .next)        [[ -f $parent/package.json ]] || continue ;;
      build)        [[ -f $parent/build.gradle || -f $parent/build.gradle.kts ]] || continue ;;
    esac
    hits+=("$hit")
  done < <(find "$root" -xdev \
      \( -name .git \
         -o -path "$HOME/.cache" \
         -o -path "$HOME/.local/share/Trash" \
         -o -path "$HOME/snap" \
         -o -path "$HOME/.var" \
         -o -path "$HOME/.npm" \
         -o -path "$HOME/.cargo/registry" \
         -o -path "$HOME/.rustup" \
      \) -prune -o \
      -type d \( -name node_modules -o -name target -o -name __pycache__ \
                 -o -name .pytest_cache -o -name .mypy_cache -o -name .ruff_cache \
                 -o -name .tox -o -name .next -o -name build \) -prune -print 2>/dev/null)

  if (( ${#hits[@]} == 0 )); then
    info "no build artifacts found"
    return 0
  fi

  # size everything, sort largest first
  local sized=() h
  for h in "${hits[@]}"; do
    sized+=("$(path_size "$h")"$'\t'"$h")
  done
  mapfile -t sized < <(printf '%s\n' "${sized[@]}" | sort -rn)

  local total=0 sz path
  for h in "${sized[@]}"; do
    sz=${h%%$'\t'*}
    path=${h#*$'\t'}
    total=$((total + sz))
    printf '  %8s  %s\n' "$(human_size "$sz")" "${path/#$HOME/\~}"
  done
  printf '  %s\n' "${C_BOLD}total: $(human_size "$total") in ${#sized[@]} directories${C_RESET}"
  info "${C_DIM}everything above can be regenerated by your build tools${C_RESET}"

  if confirm_or_dry "Delete all of these build artifacts?"; then
    for h in "${sized[@]}"; do
      safe_rm "${h#*$'\t'}"
    done
    freed_summary
  else
    info "skipped"
  fi
}
